version: '3.4'

services:

  sql.data.server:
    container_name: sql-server-2017-databases
    image: mcr.microsoft.com/mssql/server:2017-latest

  catalogservice:
    image: ${DOCKER_REGISTRY-}catalogservice
    container_name: catalogservice-container
    build:
      context: .
      dockerfile: CatalogService/Dockerfile
    depends_on:
      - sql.data.server
