version: '3.4'

services:

  sql.data.server:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04

  microcrud:
    image: ${DOCKER_REGISTRY-}microcrud
    build:
      context: .
      dockerfile: MicroCrud/Dockerfile
    depends_on:
      - sql.data.server
